language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
- gem install compass
services: mongodb
before_deploy:
- grunt build
- cd dist
deploy:
  provider: heroku
  api_key:
    secure: OPmFMZ47vcFYtv+5T0M7VRPFq0wzcwY+StBLc+psmUxPyn48BoxLpItxszudssS53f4ukoFrNNbjIhTQE07hjNQzKbga1vr7fQg+F+jRr5R/lY9GzMwIt4ROm9bkFzkPA0IxE+TxNKxxe3dFx+McT5x02zHVk0jruEbhEcHWY0Y=
  app: 
    master: saddl-api
    develop: development-saddl-api
  skip_cleanup: true
  on:
    repo: EDeijl/Saddl-API

